2016-04-16 14:42:28,166 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:44:30,927 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
2016-04-16 14:44:43,423 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
2016-04-16 14:46:27,603 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
2016-04-16 14:46:45,135 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
2016-04-16 14:46:58,980 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
2016-04-16 14:47:26,644 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:47:28,150 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:47:29,601 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:47:30,050 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:47:33,995 ERROR Internal Cubes error (NoSuchTableError): No such fact table 'fact_spending'.
2016-04-16 14:52:05,952 ERROR Exception on / [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 235, in show_index
    **info)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/templating.py", line 60, in get_source
    return loader.get_source(environment, local_name)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/jinja2/utils.py", line 151, in open_if_exists
    return open(filename, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/templates/index.html'
